# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20170529_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='ticker',
        ),
    ]
